export const sampleData = {
  SoundOfSilence: {
    images: [
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/0.png',
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/1.png',
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/2.png',
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/3.png',
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/4.png',
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/5.png',
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/6.png',
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/7.png',
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/8.png',
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/9.png',
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/10.png',
      'https://flowkeycdn.com/sheets/GzcBWKZdq64xwWPhq/300/11.png',
    ],
    id: 'WWSpLW8Xkete2z8mc',
    title: 'The Sound of Silence',
    artist: 'Simon & Garfunkel',
  },

  CanonInD: {
    images: [
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/0.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/1.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/2.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/3.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/4.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/5.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/6.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/7.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/8.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/9.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/10.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/11.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/12.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/13.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/14.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/15.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/16.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/17.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/18.png',
      'https://flowkeycdn.com/sheets/fb8yxTZbWDk2inuk8/300/19.png',
    ],
    id: '2CFkRFbWkc9kAbfNR',
    title: 'Canon in D',
    artist: 'Johann Pachelbel',
  },
};
