name: CI

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      # Install special tools for windows only
      - name: Install Windows Build Tools
        run: npm install --global windows-build-tools
        if: matrix.os == 'windows-latest'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-modules-

      - run: npm install
      - run: npm run release

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
