name: CI

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      # Install special tools for windows only
      - run: npm install --global windows-build-tools
        if: matrix.os == 'windows-latest'

      - run: npm install
      - run: npm run dist

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
